### ISSUE TITLE
Токена нет

### ISSUE THREAD

**Issue by ultrahacker678** [kotik06/VKTOOL#22]
Все сделал как написал, токен.ткст со своим токеном сделал, а показывает
error [5] User authorization failed: no access_token passed.
![Screenshot_20210901-193118_Termux](https://user-images.githubusercontent.com/55056545/131709285-bf42a0c9-6c74-41e9-8389-9b7d8385d9d7.jpg)

**Comment by 1Rayko** [comment]
скорее всего ты записал токен с пробелом
-
попробуй прочитать файл с токенами (cd VKTOOK;nano token.txt)(если nano не скачан, то pkg install nano)
