### ISSUE TITLE
Нету атрибута 'info'

### ISSUE THREAD

**Issue by VeosProductions** [kotik06/VKTOOL#23]
Я знаю что srakoeb2007.py в бета но он должен хотя бы чуть работать(пусть и не стабильно),но проблема в другом...При запуске любой утилиты может выдать подобную ошибку - AttributeError: module 'info' has no attribute 'info'.

**Comment by 1Rayko** [comment]
сначала ты должен сгенерировать конфиг

**Comment by VeosProductions** [comment]
> сначала ты должен сгенерировать конфиг
> 

Хорошо,щас попробую... благодарю (:
